server:
  port: 8082
spring:
  application:
    name: bankb
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dubbo_hmily_test2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: bigdata
    password: 123456

dubbo:
  application:
    name: bankb
  protocol:
    name: dubbo
    port: 18082
  registry:
    address: zookeeper://127.0.0.1:2181

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

org:
  dromara:
    hmily:
      serializer: kryo
      recoverDelayTime: 128
      retryMax: 10
      scheduledDelay: 128
      scheduledThreadMax: 10
      repositorySupport: db
      started: true
      hmilyDbConfig:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/tcc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
        username: bigdata
        password: 123456
