server:
  port: 8080

spring:
  application:
    name: trade-center

dubbo:
  application:
    name: trade-center
  protocol:
    name: dubbo
    port: 18080
  registry:
    address: zookeeper://127.0.0.1:2181
