server:
  port: 8081
spring:
  application:
    name: banka
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dubbo_hmily_test1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: bigdata
    password: 123456

dubbo:
  application:
    name: banka
  protocol:
    name: dubbo
    port: 18081
  registry:
    address: zookeeper://127.0.0.1:2181

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
